version: '3.9'

services:
  ai-service:
    build: ./ai-service
    container_name: ai-service
    ports:
      - "8000:8000"
    env_file:
      - ./ai-service/.env
    depends_on:
      - db

  backend-java:
    build: ./backend-java
    container_name: backend-java
    ports:
      - "8080:8080"
    env_file:
      - ./backend-java/.env
    depends_on:
      - ai-service
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend-java

  db:
    image: postgres:15
    container_name: smartgrid-db
    restart: always
    environment:
      POSTGRES_USER: smartgrid_user
      POSTGRES_PASSWORD: smartgrid_pass
      POSTGRES_DB: smartgrid
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
