
FROM node:18-alpine as build
WORKDIR /app
COPY frontend /app
RUN npm install
RUN npm run build

FROM node:18-alpine
WORKDIR /app
COPY --from=build /app/dist /app
EXPOSE 3000
CMD ["npx", "serve", "-s", "/app", "-l", "3000"]
